-- Base de origen para tests/f14_volcados.php: se crea en PostgreSQL, se vuelca con
-- pg_dump y el volcado se importa en jsonSQLDB. Los datos tienen que llegar iguales.
CREATE TABLE pedidos (id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, cliente_id integer NOT NULL, total numeric(12,2), pagado boolean DEFAULT false, creado timestamp(3) without time zone DEFAULT now(), etiquetas text[], datos jsonb);
CREATE TABLE clientes (id serial PRIMARY KEY, email character varying(120) NOT NULL UNIQUE, nombre text, saldo numeric(10,2) DEFAULT 0 CHECK (saldo > -100000), ratio double precision, activo boolean NOT NULL DEFAULT true, alta date, uid uuid, zona timestamp with time zone, foto bytea);
ALTER TABLE pedidos ADD CONSTRAINT fk_pedidos_cliente FOREIGN KEY (cliente_id) REFERENCES clientes(id) ON DELETE CASCADE;
CREATE INDEX ix_pedidos_creado ON pedidos USING btree (creado);
CREATE UNIQUE INDEX uq_clientes_nombre ON clientes (nombre);
CREATE VIEW grandes AS SELECT id, total::numeric(12,2) FROM pedidos WHERE total > 100;
CREATE FUNCTION no_negativos() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.total < 0 THEN RAISE EXCEPTION 'negativo; no'; END IF; RETURN NEW; END; $$;
CREATE TRIGGER trg_no_negativos BEFORE INSERT ON pedidos FOR EACH ROW EXECUTE FUNCTION no_negativos();
COMMENT ON TABLE clientes IS 'Clientes; con punto y coma';
INSERT INTO clientes (email, nombre, saldo, ratio, activo, alta, uid, zona, foto) VALUES
 ('ana@e.es', E'Ana O''Brien\ttab', 10.5, 0.333333333333333, true, '2026-01-02', 'a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11', '2026-01-02 03:04:05+02', NULL),
 ('bea@e.es', E'línea 1\nlínea 2 \\ barra', -3, NULL, false, NULL, NULL, NULL, '\x68656c6c6f'),
 ('cris@e.es', 'Cris 😀 emoji', 0, 1e20, true, '2026-12-31', NULL, NULL, NULL),
 ('dani@e.es', NULL, 99999.99, -2.5, true, '2026-06-15', NULL, NULL, '\xdeadbeef');
INSERT INTO pedidos (cliente_id, total, pagado, creado, etiquetas, datos) VALUES (1, 120.50, true, '2026-05-01 10:00:00.123', '{a,b}', '{"k": 1}'), (2, 0.10, false, '2026-05-02 11:00:00', NULL, NULL), (1, NULL, NULL, '2026-05-03 12:00:00', '{}', '[]');
DELETE FROM pedidos WHERE id = 2;
