--
-- PostgreSQL database dump
--

\restrict xjScKLBD0NP0KtAjfgCI7bNdxn0Bwu8iQY019aERaY1FWcWIHNJTsRR9By8chc7

-- Dumped from database version 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1)
-- Dumped by pg_dump version 16.15 (Ubuntu 16.15-0ubuntu0.24.04.1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: no_negativos(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.no_negativos() RETURNS trigger
    LANGUAGE plpgsql
    AS $$ BEGIN IF NEW.total < 0 THEN RAISE EXCEPTION 'negativo; no'; END IF; RETURN NEW; END; $$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: clientes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clientes (
    id integer NOT NULL,
    email character varying(120) NOT NULL,
    nombre text,
    saldo numeric(10,2) DEFAULT 0,
    ratio double precision,
    activo boolean DEFAULT true NOT NULL,
    alta date,
    uid uuid,
    zona timestamp with time zone,
    foto bytea,
    CONSTRAINT clientes_saldo_check CHECK ((saldo > ('-100000'::integer)::numeric))
);


--
-- Name: TABLE clientes; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.clientes IS 'Clientes; con punto y coma';


--
-- Name: clientes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.clientes_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: clientes_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.clientes_id_seq OWNED BY public.clientes.id;


--
-- Name: pedidos; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.pedidos (
    id bigint NOT NULL,
    cliente_id integer NOT NULL,
    total numeric(12,2),
    pagado boolean DEFAULT false,
    creado timestamp(3) without time zone DEFAULT now(),
    etiquetas text[],
    datos jsonb
);


--
-- Name: grandes; Type: VIEW; Schema: public; Owner: -
--

CREATE VIEW public.grandes AS
 SELECT id,
    total
   FROM public.pedidos
  WHERE (total > (100)::numeric);


--
-- Name: pedidos_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.pedidos ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.pedidos_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: clientes id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clientes ALTER COLUMN id SET DEFAULT nextval('public.clientes_id_seq'::regclass);


--
-- Data for Name: clientes; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.clientes (id, email, nombre, saldo, ratio, activo, alta, uid, zona, foto) FROM stdin;
1	ana@e.es	Ana O'Brien\ttab	10.50	0.333333333333333	t	2026-01-02	a0eebc99-9c0b-4ef8-bb6d-6bb9bd380a11	2026-01-02 01:04:05+00	\N
2	bea@e.es	línea 1\nlínea 2 \\ barra	-3.00	\N	f	\N	\N	\N	\\x68656c6c6f
3	cris@e.es	Cris 😀 emoji	0.00	1e+20	t	2026-12-31	\N	\N	\N
4	dani@e.es	\N	99999.99	-2.5	t	2026-06-15	\N	\N	\\xdeadbeef
\.


--
-- Data for Name: pedidos; Type: TABLE DATA; Schema: public; Owner: -
--

COPY public.pedidos (id, cliente_id, total, pagado, creado, etiquetas, datos) FROM stdin;
1	1	120.50	t	2026-05-01 10:00:00.123	{a,b}	{"k": 1}
3	1	\N	\N	2026-05-03 12:00:00	{}	[]
\.


--
-- Name: clientes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.clientes_id_seq', 4, true);


--
-- Name: pedidos_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.pedidos_id_seq', 3, true);


--
-- Name: clientes clientes_email_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_email_key UNIQUE (email);


--
-- Name: clientes clientes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clientes
    ADD CONSTRAINT clientes_pkey PRIMARY KEY (id);


--
-- Name: pedidos pedidos_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT pedidos_pkey PRIMARY KEY (id);


--
-- Name: ix_pedidos_creado; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_pedidos_creado ON public.pedidos USING btree (creado);


--
-- Name: uq_clientes_nombre; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_clientes_nombre ON public.clientes USING btree (nombre);


--
-- Name: pedidos trg_no_negativos; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_no_negativos BEFORE INSERT ON public.pedidos FOR EACH ROW EXECUTE FUNCTION public.no_negativos();


--
-- Name: pedidos fk_pedidos_cliente; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.pedidos
    ADD CONSTRAINT fk_pedidos_cliente FOREIGN KEY (cliente_id) REFERENCES public.clientes(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict xjScKLBD0NP0KtAjfgCI7bNdxn0Bwu8iQY019aERaY1FWcWIHNJTsRR9By8chc7

