PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;
CREATE TABLE pedidos (id INTEGER PRIMARY KEY AUTOINCREMENT, cliente_id INTEGER NOT NULL REFERENCES clientes(id) ON DELETE CASCADE, total REAL, nota TEXT, creado TEXT DEFAULT CURRENT_TIMESTAMP);
INSERT INTO pedidos VALUES(1,1,120.5,'primero','2026-03-04 05:06:07');
INSERT INTO pedidos VALUES(3,2,250.0,replace(replace('con\r\nCRLF','\r',char(13)),'\n',char(10)),'2026-03-04 05:06:07');
INSERT INTO pedidos VALUES(4,4,0.100000000000000005,'ñandú','2026-03-04 05:06:07');
CREATE TABLE clientes (id INTEGER PRIMARY KEY AUTOINCREMENT, email TEXT NOT NULL COLLATE NOCASE, nombre VARCHAR(80), saldo NUMERIC(10,2) DEFAULT 0 CHECK (saldo >= -100000), extra, alta DATE);
INSERT INTO clientes VALUES(1,'ana@e.es','Ana O''Brien',10.5,'x','2026-01-02');
INSERT INTO clientes VALUES(2,'bea@e.es',replace('Bea \nsegunda línea','\n',char(10)),-3,42,NULL);
INSERT INTO clientes VALUES(3,'cris@e.es','Cris 😀 emoji',0,NULL,'2026-12-31');
INSERT INTO clientes VALUES(4,'dani@e.es','barra \ invertida y "comillas"',99999.9900000000052,1.5,'2026-06-15');
CREATE TABLE etiquetas (codigo TEXT PRIMARY KEY, valor INTEGER) WITHOUT ROWID;
INSERT INTO etiquetas VALUES('a',1);
INSERT INTO etiquetas VALUES('b',NULL);
DELETE FROM sqlite_sequence;
INSERT INTO sqlite_sequence VALUES('clientes',4);
INSERT INTO sqlite_sequence VALUES('pedidos',4);
CREATE UNIQUE INDEX uq_email ON clientes (email);
CREATE INDEX ix_pedidos_total ON pedidos (total) WHERE total > 0;
CREATE VIEW grandes AS SELECT id, total FROM pedidos WHERE total > 100;
CREATE TRIGGER no_negativos BEFORE INSERT ON pedidos WHEN NEW.total < 0 BEGIN SELECT RAISE(ABORT, 'total negativo'); END;
COMMIT;
